### PR TITLE
Copies FAQ from wiki into repo

### PR DESCRIPTION
**Pull request by RobDolin**
By moving the FAQ from the wiki to the repo, this enables people to submit pull requests against the frequently asked questions (FAQ.)

### CODE REVIEW

**Comment by RobDolin** [comment]
Additional TODO's after this is merged:
* Update FAQ link on website (http://www.OpenLiveWriter.org/) to point to new FAQ
* Update old FAQ in wiki to point to new FAQ in repo

**Comment by ScottIsAFool** [comment]
LGTM :shipit:

**Comment by RobDolin** [comment]
Thanks @ScottIsAFool  :)

**Comment by gep13** [comment]
@RobDolin This is definitely the correct approach to allow for collaboration :+1:   Have you thought about setting up ReadTheDocs though?  It is very simple to get up and running, and means that all your documentation will be fully searchable.

**Comment by ScottIsAFool** [comment]
@gep13 can you import html files with RTD?

**Comment by gep13** [comment]
@ScottIsAFool on that one, I don't know.  I know OOTB it supports Markdown, Sphinx, and a couple others.

**Comment by ScottIsAFool** [comment]
@gep13 shame, got a lot of old html docs that would be awesome if we could import them :D

**Comment by gep13** [comment]
@ScottIsAFool here you go: https://domchristie.github.io/to-markdown/

**Comment by ScottIsAFool** [comment]
Saweeeet :)

**Comment by gep13** [comment]
Check this project for a sample that is currently using readthedocs:

https://github.com/GitTools/GitVersion/tree/master/docs

and what is rendered is here:

http://gitversion.readthedocs.org/en/latest/

and the navigation structure is controlled via this file:

https://github.com/GitTools/GitVersion/blob/master/mkdocs.yml

**Comment by RobDolin** [comment]
Per above:
>Update FAQ link on website (http://www.OpenLiveWriter.org/) to point to new FAQ
DONE

>Update old FAQ in wiki to point to new FAQ in repo
DONE

**Pull request merged**
