### PR TITLE
Fix scaling of categories dropdown and options dialog

### LINKED ISSUE #444: Categories drop-down layout messy on high DPI displays
Running on a 4K monitor, the layout looks like this:

openlivewriter categories

### PR DESCRIPTION
**Pull request by flcdrg**
Resolves #444

### CODE REVIEW

**Comment by ScottIsAFool** [comment]
LGTM. We may not have the hardware available to us in order to confirm this has fixed what it says it's fixed. Is it possible you could attach a before/after screenshot showing the actual change on screen please?

**Comment by flcdrg** [comment]
Here's the "before" screenshots:
olw categories before
olw options before

And here's the "after" ones:

olw categories after
olw options after

**Comment by ScottIsAFool** [comment]
@flcdrg Thanks for those. The options down the left, although the icons now align with the text, should each one be so big? Or does your fix not address that and this is a separate issue?

**Comment by flcdrg** [comment]
Yeah, I only tried to fix the alignment. The height is probably a separate issue - and probably relates to having some high-dpi images to display for those icons too.

**Comment by ScottIsAFool** [comment]
Ok, thanks. Your changes look good, will discuss merging them with the team possibly next week.

**Comment by kathweaver** [comment]
I've done a few blog posts and looked through things.  Nothing seems to be broken.  Changes appear to be made.

**Comment by romona** [comment]
Thank you for the work you continue to do with Open Live Writer. I
appreciate it very much.

mailto <romona@shaw.ca>:romona.king@gmail.com

WEBSITE:  http://www.northbrookdesigns.com

BLOG1: http://northbrookdesigns.blogspot.com

PINTEREST: http://pinterest.com/romonak/

**Comment by jongalloway** [comment]
Verified on high DPI monitor. Fixes #444

**Pull request merged**
