### PR TITLE
#853 Add YamlDotNet copyright to About dialog

### PR DESCRIPTION
**Pull request by caiovosilva**

### CODE REVIEW

**Comment by nvella** [comment]
Looks all good to me 😀 Thanks for your contribution!

**Comment by caiovosilva** [comment]
Hey @nvella I'm quite new to open source, should I open an pull request to the msix branch in the future?

**Comment by nvella** [comment]
The `msix` branch is currently where all our development relating to our implementation of [MSIX packaging](https://docs.microsoft.com/en-us/windows/msix/overview) is occurring. The branch was created because getting MSIX working is expected to take some time, and thus having a second branch means that the feature can be worked on without disturbing other main development. Eventually when it's all working to how we expect, the `msix` branch will be merged into `master`.

`master` was the correct branch in this case, as this specific change isn't related to the work on MSIX packaging. 👍

**Comment by caiovosilva** [comment]
Oh, thanks for explaining this @nvella !

**Pull request merged**
