### PR TITLE
rename the installer file to be more descriptive

### LINKED ISSUE #27: Rename Setup.exe
Please change the setup.exe fle on the http://openlivewriter.org/ website to something more unique please.

Not sure if this is something which should be fixed within this repo though...

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #27

I think this is Good Enough™ but let me know if I've missed something about the deployment process.

### CODE REVIEW

**Comment by andrewtobin** [comment]
Just thinking that something like OpenLiveWriterSetup.exe might be better, as OpenLiveWriter.exe by itself may make some think that it's a runnable executable and not an installer?

**Comment by shiftkey** [comment]
@tobin excellent point. Updated!

**Comment by martinwoodward** [comment]
Part of me wants to make this a COPY for now so that we don't break folks that have hard-coded links to the Setup.exe in the CDN - but update the website to the new file as soon as the build is pushed.

The other part of me figures we should just break them now so that they'll fix it as we're still very early and we want them to know they need to fix hard-coded links to Setup.exe

I don't know which part should win. I suspect I should listen to @shiftkey and go with MOVE.

Maybe we just leave the old Setup.exe in the CDN for a week and then delete it - it's not like the old Setup means you get an old version of LiveWriter.

Therefore I'm gonna go with a :+1:

**Comment by DarwinJS** [comment]
You also want "setup" in the file name because the windows loader (NTLDR) applies special compatibility tweaks to any EXE with "Setup" in it's name (or *instal* or *update*).

These tweaks will make your life much easier in the event you have something careless in your package like updating a resource that is under "Windows Resource Protection".  (you know a reg or file is under this protection if it only "TrustedInstaller" has full permissions - not even SYSTEM has full permissions - mainly files in system32, winsxs and the associated COM registrations in the 32 and 64-bit registry).

If windows *deems* you a "setup" it will lie to your setup when you try to update these and everything is a happy dance.  If you aren't deemed a setup and do such a thing - you get an error - even under admin permissions.

**Comment by shiftkey** [comment]
@martinwoodward it's barely been a week and you're already thinking about backwards compatibility :heart:

**Comment by martinwoodward** [comment]
:blush: It's a hard instinct to suppress. :shipit:

**Comment by martinwoodward** [comment]
Hey @willduff - is the script you run on the signing server checked in yet?  Just thinking that this will need updated

**Comment by willduff** [comment]
This looks good to me. I'll make sure to handle this on the next release so that we keep around both Setup.exe and OpenLiveWriterSetup.exe.

**Pull request merged**
