### PR TITLE
Fixed WordCounter regex to support Hebrew/Arabic

### PR DESCRIPTION
**Pull request by lisardggY**
The WordCounter word-counting regex explicitly ignored characters in \p{Lo} category, meaning characters in uncased scripts like Arabic or Hebrew. This caused word counts to always be off for those languages - each character would count as a word.

I've removed the \p{Lo} segment from the regex and added a handful of unit tests, both sanity checks of normal English text that worked before my change, and tests for other scripts (Hebrew, Arabic, Cyrillic).

### CODE REVIEW

**Comment by RobDolinMS** [comment]
AWESOME!  Thank you @lisardggY for submitting this PR.

**Comment by RobDolinMS** [comment]
Would be great to get some additional manual test coverage of this.

**Comment by RobDolinMS** [comment]
Also, can someone confirm Microsoft.VisualStudio.TestTools.UnitTesting is included in free versions of Visual Studio? /cc @shanselman

**Comment by lisardggY** [comment]
MSTest is available on VS2015 Community (what I used to write them). I'm _pretty_ sure it was available in VS2013 Community as well, but the Visual Studio site makes it remarkably hard to find details on older versions - all old URLs were broken when VS2015 was released. However, most release notes state that it had feature parity with VS2013 Professional, so that should be fine as well.

**Comment by jongalloway** [comment]
Thanks, @lisardggY! Bonus points for the great unit tests on this one!

**Pull request merged**
