### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by jsoref**
I was wondering if you'd be interested in this series.

You're welcome to squash commits. You're also welcome to drop words.
I haven't done any testing.
Within reason, I could probably split out some sets of changes.
I've tried to identify a couple of changes which may be slightly more significant (renaming a file, changing an api that is likely significantly public in nature). For smaller sets, I'm more careful about this, but for OpenLiveWriter, I chose not to be as careful, there are quite a few misspelled APIs, and I'm hoping it doesn't matter. 

I've skipped files that appeared to be internationalization/resource (resx) related

Generally, each commit is for a single word that was misspelled, possibly w/ many distinct misspellings.

### CODE REVIEW

**Comment by martinwoodward** [comment]
Hey, thanks very much for the PR and trying to improve the codebase, however we're focussing on getting things like Blogger working at the moment and bringing down the number of issues. While it would be great to tidy up the code a bit, we want to be careful about introducing news bugs at the moment - especially with large changes like this without much testing that will make things like the blogger fix harder to merge back in.

Hope you don't mind. Take a look at roadmap.md to get an idea where we're aiming right now.

Thanks again - great to have you on board.

**Comment by jsoref** [comment]
Would you be interested in a subset that only impacted comments?

fwiw, the roadmap is pretty much useless. it certainly doesn't indicate when you'd be interested in patches like this.

**Comment by RobDolin** [comment]
Thanks for all of this work Josh.

IMHO, Yes, if you could split into subset that just impacted comments, we could take that ASAP, and then take higher risk subset that impacts code later.

Sent from my Windows Phone
________________________________

**Comment by rebornix** [comment]
:+1: to Josh.

It would be better to squash the commits before merging it to master.

**Pull request closed without merging**
