### PR TITLE
Null ref fix

### PR DESCRIPTION
**Pull request by Gordon-Beeming**
I was getting a null ref exception when check for sub settings

### CODE REVIEW

**Comment by ScottIsAFool** [comment]
It's not easy to identify your actual changes due to the number of formatting changes that have happened in this file. Is there a reason for all these formatting changes?

**Comment by Gordon-Beeming** [comment]
I made the change before updating, I'll cancel this PR and make another. Sorry about that =).

Basically just added 

if (key == null)
{
    return false;
}

top the method

public bool HasSubSettings(string subSettingsName)

**Comment by Gordon-Beeming** [comment]
Weird, did a ctrl + K + D in Visual Studio, nothing visually changed but the formatting updated so assuming there were some characters that VS didn't recognize =D. 

Compare now shows the small change made

**Comment by ScottIsAFool** [comment]
Thanks. LGTM

**Comment by martinwoodward** [comment]
Welcome to the team Gordon!

**Pull request merged**
