### PR TITLE
use sign service v2

### PR DESCRIPTION
**Pull request by onovotny**

### CODE REVIEW

**Comment by ScottIsAFool** [comment]
@onovotny It looks like the build has failed.

**Comment by onovotny** [comment]
That appears unrelated: 
https://ci.appveyor.com/project/dotnetfoundation/openlivewriter/build/0.6.2.298-kniupplg#L251

Not sure why :/

**Comment by ScottIsAFool** [comment]
That's weird, it doesn't like "powershell"??

**Comment by jongalloway** [comment]
I'm checking with appveyor support on this - no good reason why powershell.exe wouldn't be in the path, and nothing's changed.

**Pull request merged**
