### PR TITLE
Resolve issue #377

### PR DESCRIPTION
**Pull request by kathweaver**
Changed wording on option to reflect what actually happens

### CODE REVIEW

**Comment by kathweaver** [comment]
My first code commit :-)

**Comment by RobStand** [comment]
I don't think this is the correct behavior.

**Comment by ScottIsAFool** [comment]
@RobStand see my comment on the linked issue.

**Comment by RobStand** [comment]
@ScottIsAFool So which PR should be merged?

**Comment by kathweaver** [comment]
I agree with @ScottIsAFool -- this change is consistent with behavior when publishing.  However, having an option to open the actual post when possible would be cool.  (Just checked it).

**Pull request merged**
