### PR TITLE
Fix: Google Blogger Authentication Issue [890, 887,882]

### PR DESCRIPTION
**Pull request by nithinmohantk**
#890, #887, #882, #827, #884, #883, #867, #855, #891, #892

Fixed: "Sign in with Google temporarily disabled for this app"

- upgraded .NET Framework and google dependencies to match with new HTTP requests.
- Setup new OpenLiveWriter app (API App) to communicate with Google Blogger API's and verified with local builds.
- Updated appvoyer.yml secrets

sorry for the mess with multiple pull requests. I missed making branches in a proper way.

### CODE REVIEW

**Comment by nithinmohantk** [comment]
Seems AppVoyer environment Client ID and Client Secret needs to be propagated into Project Environment settings. @jongalloway, @nvella  kindly help to make it proper.
My build is working fine with the same codebase: https://ci.appveyor.com/project/nithinmohantk/openlivewriter

**Comment by nvella** [comment]
Hi again @nithinmohantk :) It seems I didn't notice your newer PR. By policy, API client IDs and secrets aren't included into the CI build until merge. Apologies about this and I'll attempt to review as soon as I can. Please find below my original response on your older PR. Cheers 👍 Nick

---

Hi @nithinmohantk! It's very exciting to see the work you're doing. Unfortunately my life has been quite busy as of late, and as such I haven't been able to set aside enough time to contribute and maintain as I would have liked. Your contributions are very much welcome - I'll try to allocate some time over the coming week to review your PR. As for creating a branch for your work; it's not strictly required however is considered good practice - it helps if you wish to work on multiple different features or issues simultaneously.

Thanks again for your work! 👍

**Comment by nithinmohantk** [comment]
@nvella  Could you please review when you have time?.

**Comment by Matheuslaville** [comment]
Good night, I'm having an error: "See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box. ", can someone help me?

**Comment by nithinmohantk** [comment]
@Matheuslaville the config keys for Blogger need to be updated into CI build environment variables.  Since that is not yet done might be causing the error, and if blogger API  key is null .

**Comment by Matheuslaville** [comment]
> @Matheuslaville, as chaves de configuração do Blogger precisam ser atualizadas nas variáveis ​​de ambiente de criação de IC. Como isso ainda não foi feito, pode estar causando o erro e se a chave da API do blogger for nula.

Thanks for the feedback, but how can I do this procedure? I am Brazilian...

**Comment by nithinmohantk** [comment]
> > @Matheuslaville, as chaves de configuração do Blogger precisam ser atualizadas nas variáveis ​​de ambiente de criação de IC. Como isso ainda não foi feito, pode estar causando o erro e se a chave da API do blogger for nula.
> 
> Thanks for the feedback, but how can I do this procedure? I am Brazilian...

Are you the one reviewing this pull request?

**Comment by JoniWebb** [comment]
FIXED!!!!!!

Thank you so much!!!!!!!!!!!!!!!!!!!!!!!!!!!

Joni

**Comment by Matheuslaville** [comment]
> > > @Matheuslaville, as chaves de configuração do Blogger precisam ser atualizadas nas variáveis ​​de ambiente de criação de IC. Como isso ainda não foi feito, pode estar causando o erro e se a chave da API do blogger for nula.
> > 
> > 
> > Thanks for the feedback, but how can I do this procedure? I am Brazilian...
> 
> Are you the one reviewing this pull request?

Sorry for the delay, I'm looking for so many other solutions on the internet that I wasn't accessing my email, to see the notification, I just saw it now, I'm having an error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_client", Description:"Unauthorized", Uri:""
   at Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<FetchTokenAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<FetchTokenAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<ExchangeCodeForTokenAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.AuthorizationCodeInstalledApp.<AuthorizeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenLiveWriter.PostEditor.Configuration.Wizard.WeblogConfigurationWizardPanelGoogleBloggerAuthentication.<buttonLogin_Click>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OpenLiveWriter
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.exe
----------------------------------------
OpenLiveWriter.Interop
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.Interop.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
OpenLiveWriter.CoreServices
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.CoreServices.DLL
----------------------------------------
OpenLiveWriter.Localization
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.Localization.DLL
----------------------------------------
OpenLiveWriter.Controls
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.Controls.DLL
----------------------------------------
OpenLiveWriter.PostEditor
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.PostEditor.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Squirrel
    Assembly Version: 1.4.3.0
    Win32 Version: 1.4.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 9.3.0.0
    Win32 Version: 9.3.11.38370
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/Splat.DLL
----------------------------------------
OpenLiveWriter.HtmlParser
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.HtmlParser.DLL
----------------------------------------
OpenLiveWriter.Api
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.Api.DLL
----------------------------------------
OpenLiveWriter.InternalWriterPlugin
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.InternalWriterPlugin.DLL
----------------------------------------
OpenLiveWriter.ApplicationFramework
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.ApplicationFramework.DLL
----------------------------------------
OpenLiveWriter.BlogClient
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.BlogClient.DLL
----------------------------------------
OpenLiveWriter.Extensibility
    Assembly Version: 0.6.3.0
    Win32 Version: 0.6.3.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/OpenLiveWriter.Extensibility.DLL
----------------------------------------
NuGet.Squirrel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/NuGet.Squirrel.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.43.0.0
    Win32 Version: 1.43.0.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/Google.Apis.Auth.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.43.0.0
    Win32 Version: 1.43.0.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/Google.Apis.Core.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Google.Apis.Drive.v3
    Assembly Version: 1.43.0.1841
    Win32 Version: 1.43.0.1841
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/Google.Apis.Drive.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.43.0.0
    Win32 Version: 1.43.0.0
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/Google.Apis.DLL
----------------------------------------
Google.Apis.Blogger.v3
    Assembly Version: 1.43.0.1846
    Win32 Version: 1.43.0.1846
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/Google.Apis.Blogger.v3.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/mathe/AppData/Local/OpenLiveWriter/app-0.6.3/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Matheuslaville** [comment]
> Parece que o ambiente do AppVoyer ID do cliente e segredo do cliente precisam ser propagados para as configurações do ambiente de projeto. @jongalloway , @nvella ajude a torná-lo adequado.
> Minha compilação está funcionando bem com a mesma base de código: https://ci.appveyor.com/project/nithinmohantk/openlivewriter

Thanks guys from .NET, I managed to have the solution uninstalling the version from the beginning of this year by the new version of the program dated most recently by the link of nithinmohantk's comment commented on February 7th, I had already tried this link and gave this error, however, after that I uninstalled all the other versions of OLW I installed from his link I was able to log in finally and login to the Blogger system, thanks for all, and God bless this project that remains the soul for those who use BLOGGER and for bloggers in general around of the world! Anyway, gratitude, your works touch me in Brazil!

**Comment by Matheuslaville** [comment]
Unfortunately I'm having an error now to publish text, is giving this error below, can someone help me?

Google.Apis.Requests.RequestError
Access Not Configured. Drive API has not been used in project 831778163304 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=831778163304 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [403]
Errors [
	Message[Access Not Configured. Drive API has not been used in project 831778163304 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=831778163304 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.] Location[ - ] Reason[accessNotConfigured] Domain[usageLimits]
]

**Comment by nithinmohantk** [comment]
@Matheuslaville   Iam confused why are you responding to this pull request. Are you responsible for reviewing this pull request?
@nvella  can you please review and approve pull request. Also update the tokens as necessary. It has been stuck in there for more than a month,

**Comment by Matheuslaville** [comment]
> @Matheuslaville Iam confused why are you responding to this pull request. Are you responsible for reviewing this pull request?
> @nvella can you please review and approve pull request. Also update the tokens as necessary. It has been stuck in there for more than a month,

Now I managed to log in, but when publishing it you have to log in again and give an error below:

Google.Apis.Requests.RequestError
Access Not Configured. Drive API has not been used in project 831778163304 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=831778163304 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [403]
Errors [
	Message[Access Not Configured. Drive API has not been used in project 831778163304 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=831778163304 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.] Location[ - ] Reason[accessNotConfigured] Domain[usageLimits]
]

**Comment by nithinmohantk** [comment]
@jongalloway  @nvella  Could you please review this pull request. Otherwise please let me know I can close the same as well.

**Comment by RJCreationzzz** [comment]
Your build is working and we are able to sign in and publish text but as soon as we are adding images from our desktop to publish it gives below error:

Google.Apis.Requests.RequestError
Access Not Configured. Drive API has not been used in project 831778163304 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=831778163304 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [403]
Errors [
Message[Access Not Configured. Drive API has not been used in project 831778163304 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=831778163304 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.] Location[ - ] Reason[accessNotConfigured] Domain[usageLimits]
]

please help

**Comment by RJCreationzzz** [comment]
> @jongalloway @nvella Could you please review this pull request. Otherwise please let me know I can close the same as well.

Your build is working and we are able to sign in and publish text but as soon as we are adding images from our desktop to publish it gives below error:

Google.Apis.Requests.RequestError
Access Not Configured. Drive API has not been used in project 831778163304 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=831778163304 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [403]
Errors [
Message[Access Not Configured. Drive API has not been used in project 831778163304 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=831778163304 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.] Location[ - ] Reason[accessNotConfigured] Domain[usageLimits]
]

please help

**Comment by jasonbrown1965** [comment]
> 
> 
> FIXED!!!!!!
> 
> Thank you so much!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> Joni

What worked ?

**Comment by RJCreationzzz** [comment]
> FIXED!!!!!!
> 
> Thank you so much!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> Joni

Hey are you able to post images to blogger using the build mentioned on this page, because i can only login and post text using this build but as soon as i try to add some images nothing happens it just gives me error.

**Comment by JoniWebb** [comment]
> > FIXED!!!!!!
> > Thank you so much!!!!!!!!!!!!!!!!!!!!!!!!!!!
> > Joni
> 
> Hey are you able to post images to blogger using the build mentioned on this page, because i can only login and post text using this build but as soon as i try to add some images nothing happens it just gives me error.

Yes, I go to photos.google.com and then load the photos from their files.  Then I use the address on photos.google.com and insert that into the Live writer blog.  Is this what you mean?
I just tested it and it was working.
you can email me direct at cotedetexas@aol.com if you like.

Joni

**Comment by nvella** [comment]
Hi all,

Apologies for being neglectful on this issue. I was quite busy at the time it came to my attention, and to my fault it did slip out of my attention. Now that much of the world, including Australia, has gone into some form of a lockdown, I'll attempt to find sometime whilst I'm here at home to dig into this issue.

On a quick glance @nithinmohantk, I am curious as to why you changed the client ID and secret?

Cheers, Nick

**Comment by nithinmohantk** [comment]
previous application is blocked by Google, after errors. Hence created new app to verify the connectivity. You would need to update it with new App credentials or you can use mine. 

> Hi all,
> 
> Apologies for being neglectful on this issue. I was quite busy at the time it came to my attention, and to my fault it did slip out of my attention. Now that much of the world, including Australia, has gone into some form of a lockdown, I'll attempt to find sometime whilst I'm here at home to dig into this issue.
> 
> On a quick glance @nithinmohantk, I am curious as to why you changed the client ID and secret?
> 
> Cheers, Nick

Previous application is blocked by Google, after errors. Hence created new app to verify the connectivity. You would need to update it with new App credentials or you can use mine.

**Comment by RJCreationzzz** [comment]
> Hi all,
> 
> Apologies for being neglectful on this issue. I was quite busy at the time it came to my attention, and to my fault it did slip out of my attention. Now that much of the world, including Australia, has gone into some form of a lockdown, I'll attempt to find sometime whilst I'm here at home to dig into this issue.
> 
> On a quick glance @nithinmohantk, I am curious as to why you changed the client ID and secret?
> 
> Cheers, Nick

Yes dear please fix the photo uploading issue in blogger from Open Live Writer, we are able to publish text using Open Live Writer but as soon as photo is added we cannot publish adn we get error. Please waiting for the update and please update the version site officially because many people are facing issues.

**Comment by RJCreationzzz** [comment]
> Hi all,
> 
> Apologies for being neglectful on this issue. I was quite busy at the time it came to my attention, and to my fault it did slip out of my attention. Now that much of the world, including Australia, has gone into some form of a lockdown, I'll attempt to find sometime whilst I'm here at home to dig into this issue.
> 
> On a quick glance @nithinmohantk, I am curious as to why you changed the client ID and secret?
> 
> Cheers, Nick

Hello Mr. NVella I have downloaded the Nightly Build of Open Live Writer and images are uploading fine to Google Drive but not Google Photos, hence the free quota is not being used and speed of loading images from Google Drive is also not good, can you please tell how we get the old Open Live Writer back that allowed image uploading to Google Photos.

**Comment by nithinmohantk** [comment]
@nvella I am done with it.. Canceling my pull request. Thanks for the review.

**Pull request closed without merging**
