### PR TITLE
#441 added homepage link to the about screen

### PR DESCRIPTION
**Pull request by gruenwaldt**
Hi,

one time I looked for a link in the about box too.
So I added one.

Regards
Michael

### CODE REVIEW

**Comment by ScottIsAFool** [comment]
@gruenwaldt please sign the CLA request sent to you for this to be merged in.

**Comment by ScottIsAFool** [comment]
LGTM

**Comment by kzu** [comment]
Merge then? ;)

**Comment by jongalloway** [comment]
Merged. Thanks for the submission!

**Pull request merged**
