### PR TITLE
Issue #5 - Convert Google Blogger ClientLogin to OAuth 2.0

### PR DESCRIPTION
**Pull request by willduff**
The Google Blogger ClientLogin API is now deprecated, so we need to switch to OAuth 2.0. Google provides a .NET library for OAuth 2.0 and for Blogger API v3 that we can use to replace ClientLogin.

To do:
  - [x] Implement and test the Google Blogger v3 IBlogClient interface (`NewPost()`, `EditPost()`, `GetRecentPosts()`, etc)
  - [x] Implement and test Picasa image endpoint integration
  - [x] Test edge cases around revoking/expiring OAuth tokens
  - [x] Verify multiple blog support (should see the select blog panel if you have two or more Blogger blogs)
  - [ ] Enable custom web proxy support (make ShowProxySettingsLink return true)
  - [x] Verify default blog options for Google Blogger are still correct (supportsEmbeds, supportsEmptyTitles, etc.)
  - [x] Update about form to credit Google API client library for .NET and dependencies

### CODE REVIEW

**Comment by willduff** [comment]
Thanks to @guerrerotook and @asishv for writing most of this code. I'm porting it over from our bringup branch, as it wasn't quite finished yet.

**Comment by ScottIsAFool** [comment]
Question: How are we going to go about storing the clientid and client secret, given that this is an open repository? Would we really want that public?

**Comment by gep13** [comment]
When do you need this information? At compile time, or at runtime?

Sent from my Windows Phone
________________________________

**Comment by ScottIsAFool** [comment]
Run time I guess. They could be added to an xml/json file that is read in at run time, but that file would still live on user's systems and accessible to all.

**Comment by willduff** [comment]
Google acknowledges that for '[installed applications](https://developers.google.com/identity/protocols/OAuth2InstalledApp)' it's not really a secret:

>The client ID and client secret obtained from the Developers Console are embedded in the source code of your application. In this context, the client secret is obviously not treated as a secret.

@shanselman and I reached out to Google and they asked us not to check in the client id and client secret into the source. Instead, we'll generate a [client_secrets.json](https://developers.google.com/api-client-library/dotnet/guide/aaa_client_secrets) at runtime based on environment variables. Developers that want to build the source code locally will need to supply their own client ID and client secret. For the official Open Live Writer installer, we'll make sure the client ID and client secret are set to the official Open Live Writer client.

**Comment by ScottIsAFool** [comment]
I've done some work on this myself too (Blogger, not client id/secret), I have a branch here https://github.com/ScottIsAFool/OpenLiveWriter/tree/Blogger not sure how to then merge that into this pull request (should we go with it)

**Comment by willduff** [comment]
With 436f2a1, you can now successfully add a Google Blogger blog account to Writer -- with some debug asserts firing due to most of the API calls not being implemented yet. You can't post to Blogger or download anything from Blogger yet, but you will be able to soon.

**Comment by JoniWebb** [comment]
I just downloaded OWL - but of course can't open it because it won't connect to Blogger.  Is there anyway to open OWL without the authentication screen so I could at least write in OWL and the copy and paste to Blogger?  Please?  Anyone?  Dying here.

**Comment by RobStand** [comment]
@JoniWebb There is another open issue about opening OLW without adding a blog. #35

**Comment by martinwoodward** [comment]
BTW - Credits to add to AboutForm would be:

 - Google API Client Library for .NET (Apache 2.0) (C) Copyright Google Inc.\nhttps://developers.google.com/api-client-library/dotnet/
 - Apache log4net (Apache 2.0) (C) Copyright 2004-2015 The Apache Software Foundation\nhttp://logging.apache.org/log4net/
 - DotNetZip (MS-PL) Copyright (c) 2011 Dino Chiesa./nhttp://dotnetzip.codeplex.com/
 - Ionic Zlib Copyright (c) 2000,2001,2002,2003 ymnk, JCraft
 - zlib-1.1.3 Copyright (C) 1995-2004 Jean-loup Gailly and Mark Adler

**Comment by willduff** [comment]
Initial Google Blogger support is ready for testing! Going to push this to master now. We'll get a CI build dropped to the 'nightly' share and I will send out a link to anyone that wants to help test this.

**Comment by SteveP-UK** [comment]
Happy to test it for you guys!

Regards

Steve
www.StevePalmer.com
blog.StevePalmer.com
@TweetsBySteveP
+44 (0)1536 312 766
07860 639661

**Comment by danlead** [comment]
Great work willduff !!  Can you send me the link for the testing? danlead AT hotmail.it  Thanks

**Comment by justmalt** [comment]
Great work guys.  I downloaded it and I've been testing for the last hour or so.  If I should be commenting/posting elsewhere, please let me know.  A few issues I've noticed.

1) So far it allows me to add a blogger account, but when I post to that blog, the post does not appear.  OLW behaves as if it worked, but nothing shows on the blog.

2) Editing an existing post seems to work fine.

3) I can't seem to find a way to add categories/labels

4) When you create a blog account, it opens a browser window to login to google, however if you have multiple individual blogs under that account, it only allows you to choose one.  This is not a big deal but I wanted to point it out.


So far so good....not sure why the post still doesn't show.

**Comment by justmalt** [comment]
Update...seems to be a time zone thing.  Despite the time I set, the time was set 5-hours in advance making the missing posts "Scheduled" not posted.  Seems like that's OK and now if I set the time of the post BACK 5 hours, it posts just fine.

**Comment by willduff** [comment]
@justmalt For #1, did you specifically check the box to publish at a specific date and time? It would've looked like this
image

For #3, that is a known issue.

For #4 - You should have gotten an option to choose between multiple blogs. I specifically tested this scenario myself and I have reports from other users that they were able to pick between multiple blogs. Can you double check that you were logging in with the expected Google account?

**Comment by willduff** [comment]
@danlead, please see my post over in #63 - https://github.com/OpenLiveWriter/OpenLiveWriter/issues/63#issuecomment-165204083

**Comment by ScottIsAFool** [comment]
@willduff correct me if I'm wrong @justmalt, but I think what he's saying is he had multiple blogs, but he could only select one from that list, rather than be able to configure all of them? That's how I understood what was said.

**Comment by justmalt** [comment]
Yes I did check the box for a specific date/time and it was today's date and an earlier time (about 3 hours before the actual time)

I'll test 4) again.  When I clicked on the login button it opened my default browser which was not logged into the appropriate account at the time.  I logged out of the wrong account and into the appropriate google account and I don't recall it prompting but I will try it again.  That was on my testing list for today.

For whatever it is worth I was able to import the autolink list file from WLW and it seems to work OK.

**Comment by justmalt** [comment]
I also just found out I installed the nighly and not the latest general release so I'll re-install the correct release software first

**Comment by justmalt** [comment]
I reinstalled OLW and tested again.

1) The time of the post continues to be 5 hours later than the time you specify.  Confusing but fairly easy to work around.

3) I'm posting in the thread relative to missing labels ( https://github.com/OpenLiveWriter/OpenLiveWriter/issues/157#issuecomment-165465752)  And it seems like if you post in OLW, add labels in the blogger web interface the labels DO appear.  If you subsequently update that post in OLW, the labels are then removed.

4) I retested and I was able to successfully choose/add other blogs unde rthe same username so that seems OK.

**Pull request merged**
