### PR TITLE
Fix ArgumentNullException

### LINKED ISSUE #323: ArgumentNullException when getting recent posts on empty blog
I have a new blog on blogger with no posts or pages. 
When I go to "File"->"Open local draft" or "File"->"Open recent post" and on the "Open" dialog->"Open from:" list I select the item on the list with the name of my blog account 
Then I get the Unexpected Error->ArgumentNullException
image

### PR DESCRIPTION
**Pull request by ScottIsAFool**
Fixes #323

### CODE REVIEW

**Comment by hashhar** [comment]
Working fine. Can't reproduce the issue now.

**Comment by ScottIsAFool** [comment]
@hashhar To confirm, you could reproduce it previously?

**Comment by hashhar** [comment]
Yup. I tested on the `master` branch on my Windows box.

**Comment by ScottIsAFool** [comment]
Awesome, thanks.

**Pull request merged**
