### PR TITLE
Tab Index Adjustment

### PR DESCRIPTION
**Pull request by lucaslra**
Small adjustment in Tab Index of the Connection Wizard for SharePoint

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
LGTM

**Comment by martinwoodward** [comment]
@KirillOsenkov - did you happen to get chance to test against a SharePoint blog or just manually reviewed the code?

**Comment by KirillOsenkov** [comment]
@martinwoodward I know WinForms pretty well, so I just eyeballed it and it looked good. A safe change, can't make it worse ;)

**Comment by martinwoodward** [comment]
:sparkling_heart: Thanks @lucaslra - took me a while to get set up to test this one, sorry for the delay.

**Pull request merged**
