### PR TITLE
Optionsdialogbox

### PR DESCRIPTION
**Pull request by kathweaver**
Have completed test plans for Options Dialog Box

### CODE REVIEW

**Comment by kathweaver** [comment]
This should complete test plans for the majority of dialog boxes.

**Comment by hashhar** [comment]
This will make it so much easier to write unit tests now. Great work.

**Comment by kathweaver** [comment]
Is there a reason this hasn't been merged yet?

**Comment by ScottIsAFool** [comment]
Nope :)

**Pull request merged**
