### PR TITLE
Issue #224 - Google Blogger scheduled post is scheduled at the wrong time

### PR DESCRIPTION
**Pull request by willduff**
Google Blogger seems to expect local time rather than UTC time.

### CODE REVIEW

**Comment by ScottIsAFool** [comment]
LGTM.

**Comment by kathweaver** [comment]
Okay, I scheduled a post for one day out.  At 12:48 am on 2/11 CDT.  It's scheduled for 2/11/16, 10:48 PM Pacific Standard Time

**Comment by willduff** [comment]
@kathweaver Thanks for testing! Those time zones look right on. 

I've done more testing myself and found everything works correctly. Got confirmation from @SteveP-UK too. I'm going to take this fix for now so we can push out a new version that has these 3 major Blogger issues, and if users are still having issues we can fix it by having them manually change the time zone on Blogger.com to match their computer's time zone.

**Comment by kathweaver** [comment]
Sounds good to me

**Pull request merged**
