### PR TITLE
Replace Blogger Picasa integration with Google Drive upload (fixes #786)

### LINKED ISSUE #786: Error 400 - The Remote server returned an error
# Updated with Migration Instructions
I've *moved from Blogger to WordPress* to avoid this and Future errors.
## [Click here for my Step by Step Instructions and experience](https://www.vcloudinfo.com/2019/01/how-i-migrated-from-blogger-to-wordpress-on-aws-amazon-web-services.html)

-------------------------------
This issue seems to be back for me.  It just cropped up today (1/16/2019 @ 1pm) .  Was working fine yesterday at 5pm when I posted a blog article.  This issue is 100% related to images.  With no images, the blogger post post fine.  I've tried all the usual create albums fixes and my current album has a healthy 780 pictures in it.  I've also tried removing the blog and re-adding for authentication issue.  re-adds just fine.

Curious if this is just me or a wider Blogger issue. 
You can find my error log here : 
https://www.hastebin.com/ukemonuwop.sql

Thanks
CARLO

### PR DESCRIPTION
**Pull request by nvella**
Hi all,

I've successfully replaced the broken Picasa integration with Google Drive shared files. This fixes issue #786, amongst others. Upon adding a new Blogger account, OLW will now also request app-only access to the user's Google Drive, allowing OLW to create a folder for itself and upload/share files to it. Images are uploaded to this folder with GUIDs as filenames as to avoid clashes. The files are each shared individually, with the web content links being used as the image tag source and clickthrough link destination. 

I have had to upgrade Google APIs-related NuGet packages due to the inclusion of Google.Apis.Drive.v3. Due to GoogleBloggerv3Client now requesting access to the Drive API, the Open Live Writer application will require this API to be added via the Google Cloud Console. In conjunction with this, users may have to re-add their blogs if the client does not automatically detect that their token does not permit access to the Drive API.

This is my first contribution to OLW so please don't hesitate to let me know if things need a change here or there.

Kind regards, Nick.

### CODE REVIEW

**Comment by nvella** [comment]
Although the CI build passes, attempting to install the artifact fails. It states that it cannot load the Google.Apis.Drive.v3 package, despite it being restored along with the rest of the packages. Could be an issue with the CI? Install log below

```Sunday, 5 May 2019 12:22:41

Version: 0.6.3.0

OS Version: Microsoft Windows NT 6.2.9200.0
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\Users\nick\AppData\Local\OpenLiveWriter\app-0.6.3\OpenLiveWriter.exe" --squirrel-firstrun

Memory Load: 82%
Total Physical: 8094 MB
Available Physical: 1435 MB
Total Page File: 11209 MB
Available Page File: 2076 MB
Total Virtual: 2047 MB
Available Virtual: 1645 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.


System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Google.Apis.Drive.v3, Version=1.39.0.1566, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The system cannot find the file specified.
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client..cctor()
   --- End of inner exception stack trace ---
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client..ctor(Uri postApiUrl, IBlogCredentialsAccessor credentials)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenLiveWriter.BlogClient.Clients.BlogClientManager.CreateClient(String clientType, String postApiUrl, IBlogCredentialsAccessor credentials)
   at OpenLiveWriter.BlogClient.Clients.BlogClientManager.CreateClient(String clientType, String postApiUrl, IBlogCredentialsAccessor credentials, String providerId, IDictionary optionOverrides, IDictionary userOptionOverrides, IDictionary homepageOptionOverrides)
   at OpenLiveWriter.BlogClient.Clients.BlogClientManager.CreateClient(IBlogSettingsAccessor settings)
   at OpenLiveWriter.PostEditor.PostPropertyEditing.PostPropertiesBandControl.OnBlogChanged(Blog newBlog)
   at OpenLiveWriter.PostEditor.PostHtmlEditing.BlogPostHtmlEditor.OnBlogChanged(Blog newBlog)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.OnBlogChanged()
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.EditPost(IBlogPostEditingContext editingContext, Boolean forceDirty)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.Init(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorMainControl..ctor(IMainFrameWindow mainFrameWindow, IBlogPostEditingContext editingContext)
   at OpenLiveWriter.PostEditor.PostEditorForm.CreateMainControl()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnInitializeWorkspace()
   at OpenLiveWriter.PostEditor.PostEditorForm.OnInitializeWorkspace()
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.OnLoad(EventArgs e)

System.TypeInitializationException: The type initializer for 'OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Google.Apis.Drive.v3, Version=1.39.0.1566, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The system cannot find the file specified.
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client..cctor()
   --- End of inner exception stack trace ---
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client..ctor(Uri postApiUrl, IBlogCredentialsAccessor credentials)

System.IO.FileNotFoundException: Could not load file or assembly 'Google.Apis.Drive.v3, Version=1.39.0.1566, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The system cannot find the file specified.
File name: 'Google.Apis.Drive.v3, Version=1.39.0.1566, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab'
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client..cctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by nvella** [comment]
Turns out I just had to add Google Drive to the nuspec (shows how new I am to .NET haha), however it now encounters two new issues;

- OLW perpetually spawns new instances of itself. I'm not quite sure why this happens but I have a feeling it could be something to do with the auto-updater, or possibly something specific to my instance.
- Upon adding a new Blogger blog, a Google Auth invalid client/unauthorised exception is thrown. This might be due to the configuration of the OLW API app as the Drive API hasn't been enabled yet, or invalid credentials are bundled in on the CI. I've posted the log below

```Sunday, 5 May 2019 16:02:37

Version: 0.6.3.0

OS Version: Microsoft Windows NT 6.2.9200.0
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\Users\nick\AppData\Local\OpenLiveWriter\app-0.6.3\OpenLiveWriter.exe" --squirrel-firstrun

Memory Load: 57%
Total Physical: 8094 MB
Available Physical: 3456 MB
Total Page File: 9705 MB
Available Page File: 4083 MB
Total Virtual: 2047 MB
Available Virtual: 1368 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.


Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_client", Description:"Unauthorized", Uri:""
   at Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<FetchTokenAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<FetchTokenAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.Flows.AuthorizationCodeFlow.<ExchangeCodeForTokenAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.AuthorizationCodeInstalledApp.<AuthorizeAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Google.Apis.Auth.OAuth2.GoogleWebAuthorizationBroker.<AuthorizeAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpenLiveWriter.PostEditor.Configuration.Wizard.WeblogConfigurationWizardPanelGoogleBloggerAuthentication.<buttonLogin_Click>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)```

**Comment by PeterMacej** [comment]
>     * OLW perpetually spawns new instances of itself. I'm not quite sure why this happens but I have a feeling it could be something to do with the auto-updater, or possibly something specific to my instance.

It's probably the same problem as mentioned at https://github.com/OpenLiveWriter/OpenLiveWriter/issues/786#issuecomment-457068704
No fix, but a workaround is described there.

**Comment by nvella** [comment]
On inspection of the OpenLiveWriter.BlogClient.dll generated by CI, it seems that the API client secret is not being inserted by the build. As I understand this would be something the maintainers would have to fix on their end.

```
$ # After extracting the sections from the DLL
$ strings .text | grep client_secret
{ "installed": { "client_id": "597389294595-271ukaucs8ghmc6c6cnhrbef2c02g5qa.apps.googleusercontent.com", "client_secret": "PASTE_YOUR_CLIENT_SECRET_HERE" } }
```

**Comment by jongalloway** [comment]
I've enabled Google Drive API scope and am merging for testing the CI build. I've tested and this is working great for me.

I believe we don't insert the client secret on AppVeyor CI builds, possibly for security - not sure (@onovotny ?).

**Comment by arshali** [comment]
Thanks for ur contribution

**Comment by wcbx** [comment]
I appreciate your contribution. I've tested it and it seems to work fine. However, I have two major complaints. One complaint is that since it uploads to google drive the "lightbox" image viewer doesn't work with the linked images so if you upload multiple images you can't get a nice slide of images to scroll through. My second complaint is that if you upload images to google photos you have the option to use a compression algorithm with your upload which doesn't count against your 15 GB limit. Presumably if we use Google Drive to upload our images we can't utilize that Blogger feature.

**Pull request merged**
